### PR TITLE
Add ignoring of duplicate 'css' classes

### LINKED ISSUE #138: Feat request: Should ignore duplicates in class names list
`<div class="popup welcome popup popup welcome"></div>`
should be equivalent to
`<div class="welcome popup"></div>`

### PR DESCRIPTION
**Pull request by eGavr**
closes #138 

/cc @zxqfox

### CODE REVIEW

**Comment by zxqfox** [comment]
:shipit:

**Comment by zxqfox** [comment]
@tadatuta Can you please look at this PR and tell us your wise opinion about duplications in classes? 
Can it be important for someone?
Should there be an option to compare class attributes more accurately?

**Comment by tadatuta** [comment]
@zxqfox 
I understand that duplicate classes do no harm but why should we consider HTML with them identical? Isn't duplication a result of some issues with templates?

**Comment by zxqfox** [comment]
@tadatuta I described my position in #138. It's the same for browser, so there is no real difference. Gzip will help you if your template contains repeats. Moreover, if somebody need it for real cases, we can add an option. Atm we can't disable this check (as well as sorting classes, and a lot of other assumptions).

**Comment by tadatuta** [comment]
> there is no real difference

as I wrote above I know there's no difference for **browsers** but it **may** be for template engines or templates.

> if somebody need it for real cases

can't imagine any ;)

**Comment by zxqfox** [comment]
:yellow_heart: <3 :yellow_heart: Thanks!

**Pull request merged**
